FROM astrocrpublic.azurecr.io/runtime:3.0-14

# The Astronomer Runtime base image declares an ONBUILD chain that handles
# the full image-build pipeline automatically:
#
#   ONBUILD COPY packages.txt .
#   ONBUILD RUN /usr/local/bin/install-system-packages       # runs as root
#   ONBUILD COPY requirements.txt .
#   ONBUILD RUN /usr/local/bin/install-python-dependencies   # runs as root
#   ONBUILD COPY --chown=astro:0 . .                         # drops to astro UID
#
# Anything we add to this Dockerfile after the FROM runs AFTER that final
# `COPY --chown=astro:0`, i. e. as the unprivileged `astro` user, so any
# additional `apt-get update`/`apt-get install` would fail with
# `Permission denied`. There is also no need: every customisation we want
# is already expressed via the two files the ONBUILD chain consumes.
#
# Conventions enforced by this project so the ONBUILD chain just works:
#
# * `packages.txt` lists apt packages installed by `install-system-packages`.
#   Currently it contains `git`, required at build time so uv can clone the
#   `acidbase @ git+https://github.com/jurdabos/acidbase.git` dependency
#   declared in `requirements.txt`. Without it uv fails with
#       "Git executable not found. Ensure that Git is installed and available."
#
# * `requirements.txt` is autogenerated by `scripts/sync_requirements.py`
#   from `pyproject.toml`'s `[project].dependencies`, with the Airflow core
#   packages (`apache-airflow`, `apache-airflow-core`,
#   `apache-airflow-task-sdk`) filtered out. The runtime's
#   `install-python-dependencies` step rejects any `apache-airflow` pin
#   here ("Do not upgrade by specifying 'apache-airflow' in your
#   requirements.txt, change the base image instead!"). A local pre-commit
#   hook keeps the file in sync; never edit it by hand.
#
# If you ever need root-level Dockerfile customisation, switch user back
# with `USER root` (and `USER astro` afterwards) per Astronomer's docs.
