FROM astrocrpublic.azurecr.io/runtime:3.0-14

# IMPORTANT: the Astronomer Runtime base image declares ONBUILD triggers
# that already do the following automatically right after this FROM:
#   ONBUILD COPY packages.txt .       ; ONBUILD RUN install-system-packages
#   ONBUILD COPY requirements.txt .   ; ONBUILD RUN install-python-dependencies
# The `install-python-dependencies` script REFUSES to install Airflow itself
# from requirements.txt ("Do not upgrade by specifying 'apache-airflow' in
# your requirements.txt, change the base image instead!"). For that reason
# `requirements.txt` is autogenerated by `scripts/sync_requirements.py`,
# which strips the Airflow core packages out of pyproject.toml's deps.
# A pre-commit hook keeps that file in sync; never edit it by hand.
#
# The COPY/RUN lines below are explicit reinforcements of the ONBUILD
# behaviour. They are idempotent: pip installs from the same
# requirements.txt the ONBUILD step already used, so reruns are no-ops.

# Installing OS-level (apt) packages; packages.txt may be empty
COPY packages.txt .
RUN if [ -s packages.txt ]; then \
        apt-get update && \
        xargs -a packages.txt apt-get install -y --no-install-recommends && \
        rm -rf /var/lib/apt/lists/*; \
    fi

# Installing extra Python deps (Airflow itself is provided by the runtime).
# requirements.txt is direct-deps-only and auto-generated; see
# scripts/sync_requirements.py and pyproject.toml.
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
