#!/usr/bin/env python3
"""
Regenerate ``requirements.txt`` from ``pyproject.toml`` direct dependencies.

Background
----------
The Astronomer Runtime base image (``astrocrpublic.azurecr.io/runtime:*``)
ships Apache Airflow itself plus a curated set of core companions
(``apache-airflow-core``, ``apache-airflow-task-sdk``). Its ONBUILD step
``/usr/local/bin/install-python-dependencies`` runs ``pip install`` against
the project's ``requirements.txt`` and *refuses* if it sees the
``apache-airflow`` meta-package, failing the image build with::

    Do not upgrade by specifying 'apache-airflow' in your requirements.txt,
    change the base image instead!

At the same time, local development uses ``uv sync`` against
``pyproject.toml`` and *does* want Airflow installed in ``.venv`` so DAGs
and the Jinja-macro plugin can be imported by ``pytest``. Hence the two
files diverge intentionally:

* ``pyproject.toml``   \u2192 full direct deps (includes ``apache-airflow``)
* ``requirements.txt`` \u2192 same set minus the Airflow core packages

This script enforces the divergence deterministically: it reads
``[project].dependencies`` from ``pyproject.toml`` (stdlib ``tomllib``
only \u2014 no third-party deps), filters out the Airflow core meta-packages,
and writes ``requirements.txt`` with a clear "do not edit by hand"
header. The companion pre-commit hook (see ``.pre-commit-config.yaml``)
runs the script on every commit that touches ``pyproject.toml`` or
``requirements.txt`` so the two cannot drift back into the broken state.

Usage
-----
::

    python scripts/sync_requirements.py

Exits 0 if the file was already in sync; exits 1 if it had to rewrite the
file (so that pre-commit fails loudly and prompts the user to re-stage).
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PYPROJECT = PROJECT_ROOT / "pyproject.toml"
REQUIREMENTS = PROJECT_ROOT / "requirements.txt"

# Packages shipped by the Astronomer Runtime base image. The
# ``install-python-dependencies`` ONBUILD guard specifically rejects
# the ``apache-airflow`` meta-package; the other two are filtered for
# the same conceptual reason (they're part of the runtime, not user
# requirements). Apache-airflow PROVIDERS (e. g.
# ``apache-airflow-providers-smtp``) are user-installable add-ons and
# stay in the file.
EXCLUDED_NAMES: frozenset[str] = frozenset(
    {
        "apache-airflow",
        "apache-airflow-core",
        "apache-airflow-task-sdk",
    }
)

# Captures the leading distribution name from a PEP 508 dep spec, e. g.
# "apache-airflow", "openai", "pinecone[grpc]", "acidbase @ git+https://..."
NAME_RE = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)\b")

HEADER = """\
# This file is autogenerated by scripts/sync_requirements.py from the
# [project].dependencies block of pyproject.toml, minus the Apache
# Airflow core packages (apache-airflow, apache-airflow-core,
# apache-airflow-task-sdk) which the Astronomer Runtime base image
# already provides.
#
# Including those packages here triggers the runtime's ONBUILD guard:
#   "Do not upgrade by specifying 'apache-airflow' in your
#    requirements.txt, change the base image instead!"
# and the Docker build fails.
#
# DO NOT edit this file by hand. To change deps, edit pyproject.toml
# and run:    python scripts/sync_requirements.py
# (the pre-commit hook does this automatically on each commit).
"""


def normalize_name(spec: str) -> str:
    """Returns the PEP 503-normalized package name from a dependency spec."""
    match = NAME_RE.match(spec)
    if not match:
        raise ValueError(f"Could not parse dependency spec: {spec!r}")
    return match.group(1).lower().replace("_", "-")


def render_requirements(deps: list[str]) -> tuple[str, list[str], list[str]]:
    """Returns (rendered text, kept specs, dropped specs)."""
    kept: list[str] = []
    dropped: list[str] = []
    for spec in deps:
        if normalize_name(spec) in EXCLUDED_NAMES:
            dropped.append(spec)
        else:
            kept.append(spec)
    body = "\n".join(kept) + ("\n" if kept else "")
    return HEADER + body, kept, dropped


def main() -> int:
    if not PYPROJECT.exists():
        print(f"error: {PYPROJECT} not found", file=sys.stderr)
        return 2
    data = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    deps = data.get("project", {}).get("dependencies", [])
    if not deps:
        print("error: no [project].dependencies in pyproject.toml", file=sys.stderr)
        return 2
    new_content, kept, dropped = render_requirements(deps)
    old_content = REQUIREMENTS.read_text(encoding="utf-8") if REQUIREMENTS.exists() else ""
    if new_content == old_content:
        print("requirements.txt is in sync with pyproject.toml.")
        return 0
    REQUIREMENTS.write_text(new_content, encoding="utf-8")
    print(f"Wrote {REQUIREMENTS.relative_to(PROJECT_ROOT)} ({len(kept)} kept, {len(dropped)} dropped from base image).")
    for d in dropped:
        print(f"  - filtered (provided by Astro Runtime image): {d}", file=sys.stderr)
    # Non-zero exit so pre-commit reports the rewrite and asks for re-staging.
    return 1


if __name__ == "__main__":
    sys.exit(main())
